package: yduplicate
version: '0.0.0-dev'
author: Thomas Blum
supportpage:

page:
    title: YDuplicate
    icon: rex-icon fa-files-o
    subpages:
        setup: { title: 'translate:setup', perm: admin }
        finder: { title: 'translate:finder', perm: 'yduplicate[finder]' }

requires:
    redaxo: ^5.8
    php: ^7.3
